name: pub_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  auto_size_text: ^3.0.0
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll.git
  copy_with_extension: ^5.0.3
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.1.0
  isar: 4.0.0-dev.10
  isar_flutter_libs: 4.0.0-dev.10
  json_annotation: ^4.8.1
  markdown: ^7.1.1
  pub_semver: ^2.1.4
  pubspec: ^2.3.0
  pubspec_parse: ^1.2.3
  riverpod: ^2.3.6
  shimmer: ^3.0.0
  tar: ^0.5.6
  timeago: ^3.5.0
  url_launcher: ^6.1.12
  go_router: ^10.0.0
  flutter_svg: ^2.0.7
  flutter_html: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  path_provider: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.3
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/ff_banner.png
    - assets/pub_logo.svg
    - assets/pub_logo_dark.svg
    - assets/search_bg.svg
