name: pub_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

isar_version: &isar_version 3.0.2 # define the version to be used

dependencies:
  auto_size_text: ^3.0.0
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll.git
  copy_with_extension: ^4.0.3
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  google_fonts: ^3.0.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  json_annotation: ^4.6.0
  markdown: ^6.0.0
  pub_semver: ^2.1.1
  pubspec: ^2.3.0
  pubspec_parse: ^1.2.1
  riverpod: ^2.0.0
  shimmer: ^2.0.0
  tar: ^0.5.6
  timeago: ^3.3.0
  url_launcher: ^6.1.5
  go_router: ^5.0.0
  flutter_svg: ^1.1.5
  flutter_html: ^3.0.0-alpha.6
  flutter_html_svg: ^3.0.0-alpha.4

dev_dependencies:
  build_runner: ^2.0.0
  copy_with_extension_gen: ^4.0.3
  isar_generator: *isar_version
  json_serializable: ^6.3.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/ff_banner.png
    - assets/pub_logo.svg
    - assets/pub_logo_dark.svg
    - assets/search_bg.svg
