[package]
name = "mdbx-sys"
version = "0.0.0"
edition = "2021"

[lib]
name = "mdbx_sys"

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1"
cc = "1.0"
bindgen = { version = "0.63", default-features = false, features = ["runtime"] }
