name: isar_flutter_libs
description: Isar Core binaries for the Isar Database. Needs to be included for Flutter apps.
version: 3.0.5
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 3.0.5

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libs
        pluginClass: IsarFlutterLibsPlugin
      ios:
        pluginClass: IsarFlutterLibsPlugin
      macos:
        pluginClass: IsarFlutterLibsPlugin
      linux:
        pluginClass: IsarFlutterLibsPlugin
      windows:
        pluginClass: IsarFlutterLibsPlugin
