name: isar_flutter_libs
description: Isar Core binaries for the Isar Database. Needs to be included for Flutter apps.
version: 4.0.0-dev.14
repository: https://github.com/isar/isar
homepage: https://isar.dev
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  isar:
    git:
      url: https://github.com/pmathulan/isar_db.git
      path: packages/isar
      ref: isar_flutter_libs_dev

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libs
        pluginClass: IsarFlutterLibsPlugin
      ios:
        pluginClass: IsarFlutterLibsPlugin
      macos:
        pluginClass: IsarFlutterLibsPlugin
      linux:
        pluginClass: IsarFlutterLibsPlugin
      windows:
        pluginClass: IsarFlutterLibsPlugin
      web:
