name: isar_flutter_libs
description: Isar Core binaries for the Isar Database. Needs to be included for Flutter apps.
version: 3.0.6-dev.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 3.0.6-dev.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libs
        pluginClass: IsarFlutterLibsPlugin
      ios:
        pluginClass: IsarFlutterLibsPlugin
      macos:
        pluginClass: IsarFlutterLibsPlugin
      linux:
        pluginClass: IsarFlutterLibsPlugin
      windows:
        pluginClass: IsarFlutterLibsPlugin
