name: isar_flutter_libs
description: Flutter binaries for the Isar Database. Needs to be included for Flutter apps.
version: 2.0.0-dev.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 2.0.0-dev.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libs
        pluginClass: IsarFlutterLibsPlugin
      ios:
        pluginClass: IsarFlutterLibsPlugin
      macos:
        pluginClass: IsarFlutterLibsPlugin
      linux:
        pluginClass: IsarFlutterLibsPlugin
      windows:
        pluginClass: IsarFlutterLibsPlugin