name: isar_flutter_libs
description: Isar Core binaries for the Isar Database. Needs to be included for Flutter apps.
version: 0.0.0-placeholder
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  isar:
    path: ../isar

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libs
        pluginClass: IsarFlutterLibsPlugin
      ios:
        pluginClass: IsarFlutterLibsPlugin
      macos:
        pluginClass: IsarFlutterLibsPlugin
      linux:
        pluginClass: IsarFlutterLibsPlugin
      windows:
        pluginClass: IsarFlutterLibsPlugin
      web:
