name: isar_flutter_libs
description: Flutter binaries for the Isar Database. Needs to be included for Flutter apps.
version: 1.0.0+1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ">=1.0.0 <1.1.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libs
        pluginClass: IsarFlutterPlugin
      ios:
        pluginClass: IsarFlutterPlugin