[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,--hash-style=both"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-Wl,--hash-style=both"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-Wl,--hash-style=both"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-Wl,--hash-style=both"]
