name: isar_test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar: any
  isar_flutter_libs: any
  path_provider: any
  freezed_annotation: any
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  isar_generator: any
  freezed: any
  test: ^1.20.1
  flutter_lints: ^1.0.4

dependency_overrides:
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
  isar_generator:
    path: ../isar_generator
  test_api: ^0.4.9
