name: isar_test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl: ^0.20.2
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
  json_annotation: ^4.8.1
  meta: ^1.16.0
  path: ^1.8.3
  path_provider: ^2.0.15
  test: any

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

dependency_overrides:
  dart_style: ^3.0.1
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
