name: counter
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 4.0.0-dev.10
  isar_flutter_libs: ^4.0.0-dev.10

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  dart_style: ^3.0.1

flutter:
  uses-material-design: true
