name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
version: 0.4.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  isar: 0.4.0
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^1.0.0
  glob: ^2.0.0
  path: ^1.6.0
  dart_style: ^2.0.0
  json_annotation: ^4.0.0
  dartx: ^0.7.0
  freezed_annotation: ^0.14.1

dev_dependencies:
  json_serializable: ^4.0.0
  build_runner: ^1.12.1
  freezed: ^0.14.1

#dependency_overrides:
#  isar:
#    path: ../isar
