name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
version: 3.0.0-dev.1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  isar: 3.0.0-dev.1
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.1.0
  glob: ^2.0.2
  path: ^1.8.1
  dart_style: ^2.2.3
  dartx: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
