name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.0.6-dev.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=4.6.0 <6.0.0"
  build: ^2.3.0
  dart_style: ^2.2.3
  dartx: ^1.1.0
  glob: ^2.0.2
  isar: 3.0.6-dev.0
  path: ^1.8.1
  source_gen: ^1.2.2
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^2.1.5
  matcher: ^0.12.12
  test: ^1.21.0
  very_good_analysis: ^3.0.1
