name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
version: 1.0.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  isar: 1.0.0
  build: ^2.1.0
  source_gen: ^1.0.5
  analyzer: ^2.0.0
  glob: ^2.0.1
  path: ^1.8.0
  dart_style: ^2.0.3
  json_annotation: ^4.1.0
  dartx: ^0.7.0
  freezed_annotation: ^0.14.3

dev_dependencies:
  json_serializable: ^5.0.0
  build_runner: ^2.1.1
  freezed: ^0.14.5
  lints: ^1.0.1
