name: isar
description: Extremely fast, easy to use, and fully async NoSQL database for Flutter.
version: 0.0.0-placeholder
repository: https://github.com/isar/isar/tree/main/packages/isar
homepage: https://github.com/isar/isar
issue_tracker: https://github.com/isar/isar/issues
documentation: https://isar.dev
funding:
  - https://github.com/sponsors/simc/
topics:
  - database
  - isar
  - sqlite
  - encryption
  - storage

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  analyzer: ">=6.5.0 <8.0.0"
  build: ^2.4.1
  ffi: ">=2.0.0 <3.0.0"
  meta: ^1.16.0
  source_gen: ^2.0.0
  web: ^1.1.0

dev_dependencies:
  build_test: ^2.2.0
  ffigen: ^19.0.0
  test: any
  very_good_analysis: ^8.0.0
