name: isar
description: Extremely fast, easy to use, and fully async NoSQL database for Flutter.
version: 3.0.0-dev.12
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: '>=2.0.0 <3.0.0'
  js: ^0.6.4
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^6.0.1
  test: ^1.21.1
  very_good_analysis: ^3.0.1
