name: isar
description: Fast Cross Platform Database for Flutter & Web Apps. Supports indexes, FTS, queries etc.
version: 1.0.0+1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
  ffigen: ^3.0.0
  lints: ^1.0.1
