name: isar
description: Extremely fast, easy to use, and fully async NoSQL database for Flutter.
version: 4.0.0-dev.2
repository: https://github.com/isar/isar/tree/main/packages/isar
homepage: https://github.com/isar/isar
issue_tracker: https://github.com/isar/isar/issues
documentation: https://isar.dev
funding:
  - https://github.com/sponsors/simc/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.2.0 <6.0.0"
  build: ^2.3.1
  ffi: ">=2.0.0 <3.0.0"
  meta: ^1.7.0
  source_gen: ^1.2.7

dev_dependencies:
  build_test: ^2.2.0
  ffigen: ^8.0.0
  test: any
  very_good_analysis: ^3.0.1
