name: isar
description: Extremely fast, easy to use, and fully async NoSQL database for Flutter.
version: 0.0.0-placeholder
repository: https://github.com/isar/isar/tree/main/packages/isar
homepage: https://github.com/isar/isar
issue_tracker: https://github.com/isar/isar/issues
documentation: https://isar.dev
funding:
  - https://github.com/sponsors/simc/
topics:
  - database
  - isar
  - sqlite
  - encryption
  - storage

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ">=5.2.0 <7.0.0"
  build: ^2.3.1
  ffi: ">=2.0.0 <3.0.0"
  js: ^0.6.7
  meta: ^1.9.1
  source_gen: ^1.5.0

dev_dependencies:
  build_test: ^2.2.0
  ffigen: ^10.0.0
  test: any
  very_good_analysis: ^5.1.0
