name: isar
description: Extremely fast, easy to use, and fully async NoSQL database for Flutter.
version: 3.1.0+2
repository: https://github.com/isar/isar/tree/main/packages/isar
homepage: https://github.com/isar/isar
issue_tracker: https://github.com/isar/isar/issues
documentation: https://isar.dev
funding:
  - https://github.com/sponsors/leisim/

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  ffi: ">=2.0.0 <3.0.0"
  js: ^0.7.1
  meta: ^1.11.0

dev_dependencies:
  build_test: ^2.2.0
  ffigen: ^12.0.0
  test: any
  very_good_analysis: ^5.1.0
