name: isar_test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: any
  isar_flutter_libs: any
  path_provider: any

dev_dependencies:
  build_runner: any
  isar_generator: any
  flutter_driver:
    sdk: flutter
  test: any

dependency_overrides:
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
  isar_generator:
    path: ../isar_generator
  build: ^2.0.0
  crypto: ^3.0.0
  convert: ^3.0.0