name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 2.4.0
  vm_service: ^7.2.0
  provider: ^5.0.0
  dartx: ^1.0.0
  json_annotation: ^4.0.0
  petitparser: ^4.0.2
  linked_scroll_controller: ^0.2.0
  flutter_svg: any
  font_awesome_flutter: any
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.0
  build_runner: any
  flutter_lints: ^1.0.4

dependency_overrides:
  isar:
    path: ../isar

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
