name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll
  flutter:
    sdk: flutter
  flutter_svg: any
  font_awesome_flutter: any
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  isar:
    path: ../isar
  vm_service: ^15.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
