name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dartx: ^1.0.0
  file_picker: ^5.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.7
  flutter_svg: any
  flutter_treeview: ^1.0.7+1
  font_awesome_flutter: any
  go_router: ^4.1.0
  google_fonts: ^3.0.1
  isar: any
  vm_service: ^9.0.0
  web_socket_channel: ^2.2.0
  

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.1
  very_good_analysis: ^3.0.1

dependency_overrides:
  ffi: '>=2.0.0 <3.0.0'

  isar:
    path: ../isar

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
