name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll
  flutter:
    sdk: flutter
  flutter_svg: any
  font_awesome_flutter: any
  go_router: ^5.0.0
  google_fonts: ^3.0.1
  isar:
    path: ../isar
  vm_service: ^9.0.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.1
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
