name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  isar:
    path: ../isar
  vm_service: ^15.0.0
  web: ^1.1.1
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_lints: ^6.0.0

dependency_overrides:
  dart_style: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
